[package]
name = "meowww"
version = "1.3.0"
authors = ["Fran√ßois Gindraud <francois.gindraud@univ-lyon1.fr>"]
description = "Simple stateless chat server with websockets"

[dependencies]
rouille = "2"
horrorshow = "0.6"
clap = "2"
rust-embed = "3"
serde = "1"
serde_derive = "1"
serde_json = "1"
